const DETAIL_CARD_OPEN = 'DETAIL_CARD_OPEN';
const DETAIL_CARD_CLOSE = 'DETAIL_CARD_CLOSE';
const WEATHER_API_REQUEST = 'WEATHER_API_REQUEST';
const WEATHER_API_REQUEST_SUCCESS = 'WEATHER_API_REQUEST_SUCCESS';
const WEATHER_API_REQUEST_FAILURE = 'WEATHER_API_REQUEST_FAILURE';

export {
  DETAIL_CARD_OPEN,
  DETAIL_CARD_CLOSE,
  WEATHER_API_REQUEST,
  WEATHER_API_REQUEST_SUCCESS,
  WEATHER_API_REQUEST_FAILURE,
};
